name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/health-app:latest ./app
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/health-app:latest

    - name: Restart Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.health-app-2041 }}
