name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: az acr login --name myregistry2041

    - name: Build and Push Docker Image
      run: |
        docker build -t myregistry2041.azurecr.io/health-app:latest ./app
        docker push myregistry2041.azurecr.io/health-app:latest
